Fix pointer math.
The previous use of `get_unchecked` was UB according to
https://doc.rust-lang.org/nightly/std/primitive.slice.html#safety-2
and https://github.com/rust-lang/rust/pull/120594 exposed this leading
to a panic caught by out tests as:
```
cargo test --all
...
thread 'fold::tests::ident_transformation_in_defs' panicked at library/core/src/panicking.rs:155:5:
unsafe precondition(s) violated: hint::assert_unchecked must never be called when the condition is false
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `-p garando_syntax --lib`
...
```

Fixes https://github.com/rust-lang/rust/issues/120910